### ISSUE TITLE
There is no ChinoApiException.cs file

### ISSUE THREAD

**Issue by bastiankayser** [chinoio/chino-dotnet#1]
Hi,

the Chino.csproj expects a ChinoApiException.cs file, which is not commited.

**Comment by aarighi** [comment]
Seems that it was accidentally removed together with file `Chino.sln` in the last commit. Running tests...

**Comment by aarighi** [comment]
Tests passing. The new files can be found in release [1.0.2-alpha.2](https://github.com/chinoio/chino-dotnet/tree/1.0.2-alpha.2)

I am closing this issue.
