### ISSUE TITLE
Dependency RestSharp 106.6.8 no longer on nuget

### ISSUE THREAD

**Issue by bastiankayser** [chinoio/chino-dotnet#2]
Unfortunately ResSharp has no longer a version 106.6.8 on nuget:
https://www.nuget.org/packages/RestSharp
Therefore nuget package restore fails.
Switch to 106.6.9 seems to work.

**Comment by aarighi** [comment]
Glad to know it still works.

Let me know if you have problems with the new version. Meanwhile, I will update the dependency, run tests and check that nothing is broken.

**Comment by aarighi** [comment]
Upgraded. I'm closing this issue
